### Регистрация
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "qwer",
  "email": "qwert@gmail.com",
  "password": "1234"
}

### Авторизация
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "qwert@gmail.com",
  "password": "1234"
}

### Создать пост (нужно вставить токен)
POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDVjN2IwYjExZTg3ZWUwNTViYWRhYyIsImlhdCI6MTc2MTk5MDMyMCwiZXhwIjoxNzYyMDc2NzIwfQ.xull_esqGZZuiXM3RhNc6MQayH_dm8EvGRgoU1pWE7c

{
  "title": "Мой первый пост1234",
  "content": "Это тестовый контент"
}


### Получить все посты
GET http://localhost:5000/posts

### Получить пост по ID
GET http://localhost:5000/posts/



###Обновить пост по ID,TOKEN
PUT http://localhost:5000/posts/6905d84eced18411e31c2de7
Content-Type: application/json
Authorization: Bearer 

{
  "title": "Обновлённый пост123456789",
  "content": "Новое содержимое"
}


###Удалить пост по ID,TOKEN
DELETE http://localhost:5000/posts/6905dc40469859d19bcf1139
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDVjN2IwYjExZTg3ZWUwNTViYWRhYyIsImlhdCI6MTc2MTk5MjM4NywiZXhwIjoxNzYyMDc4Nzg3fQ.CbSxIX2OwaEPVcBffssh3Rare3j3FvqlbqdK_Zz2wEQ